[phases.setup]
nixPkgs = [
    "pkgs.apacheHttpd",
    "pkgs.php.extensions.pdo_pgsql",
    "pkgs.php.extensions.bcmath",
    "pkgs.php.extensions.gd",
    "pkgs.php.extensions.intl",
    "pkgs.php.extensions.mbstring",
    "pkgs.php.extensions.zip"
]
